CREATE TABLE IF NOT EXISTS welpodron_form_schema
(
	ID INT(11) NOT NULL AUTO_INCREMENT,
	SCHEMA_JSON TEXT NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS welpodron_form_request
(
	ID INT(11) NOT NULL AUTO_INCREMENT,
	FORM_ID TEXT,
  SCHEMA_ID INT(11),
  USER_ID TEXT,
  SESSION_ID TEXT,
  IP TEXT,
  PAGE TEXT,
  USER_AGENT TEXT,
  DATE_CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PAYLOAD TEXT,
	PRIMARY KEY (ID)
);